steps:

  # Show gcloud config.
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Show config of Google Cloud SDK"
    args:
      - config
      - list

  - name: "gcr.io/cloud-builders/docker"
    id: "Build Docker image"
    dir: cloudrun
    args:
      - build
      - --tag
      - gcr.io/${PROJECT_ID}/ai-platform-notification:${TAG_NAME:1}
      - --tag
      - gcr.io/${PROJECT_ID}/ai-platform-notification:latest
      - .

images:
  - gcr.io/${PROJECT_ID}/ai-platform-notification:${TAG_NAME:1}
  - gcr.io/${PROJECT_ID}/ai-platform-notification:latest
