steps:

  # Show gcloud config.
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Show config of Google Cloud SDK"
    args:
      - config
      - list

  - name: "gcr.io/cloud-builders/docker"
    id: "Build Docker image"
    dir: functions
    args:
      - build
      - --tag
      - gcr.io/${PROJECT_ID}/ai-platform-notification:${_DOCKER_TAG}
      - --tag
      - gcr.io/${PROJECT_ID}/ai-platform-notification:latest
      - .

substitutions:
  _DOCKER_TAG: ${TAG_NAME:1}

options:
  dynamic_substitutions: true

images:
  - gcr.io/${PROJECT_ID}/ai-platform-notification:${_DOCKER_TAG}
  - gcr.io/${PROJECT_ID}/ai-platform-notification:latest
